[theme]
primaryColor = "#F3A950"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8F6"
textColor = "#0D0D0D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
